remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
title: Terence Ordona - frontend developer
description: OSS Unofficial Builds for Windows on Arm
url: 'https://github.com/tordona'