remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false,
title: Terence Ordona,
description: Building and compiling open source software for native Windows on Arm,
url: 'https://github.com/tordona'
site: {
  show_downloads: false,
  title: random developer,
  description: Building and compiling open source software for native Windows on Arm,
  url: 'https://github.com/tordona'
}
